build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base"
  amd64: "ghcr.io/home-assistant/amd64-base"
  armhf: "ghcr.io/home-assistant/armhf-base"
  armv7: "ghcr.io/home-assistant/armv7-base"
  i386: "ghcr.io/home-assistant/i386-base"
labels:
  org.opencontainers.image.title: "Syslog"
  org.opencontainers.image.description: "Send your HAOS logs to a remote syslog server"
  org.opencontainers.image.source: "https://github.com/mib1185/ha-addon-syslog"
  org.opencontainers.image.licenses: "Apache License 2.0"
